apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-config-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-config-app
  template:
    metadata:
      labels:
        app: spring-config-app
    spec:
      containers:
        - name: spring-container
          image: spring-server:env
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MY_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: my-account
            - name: MY_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: my-password
