apiVersion: v1
kind: Service
metadata:
  name: spring-config-service
spec:
  type: NodePort
  selector:
    app: spring-config-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
